/*
 * This file is generated by jOOQ.
 */
package com.jobster.server.model.tables;


import com.jobster.server.model.Indexes;
import com.jobster.server.model.Jobster;
import com.jobster.server.model.Keys;
import com.jobster.server.model.tables.records.OfferFormationRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OfferFormation extends TableImpl<OfferFormationRecord> {

    private static final long serialVersionUID = 1647109784;

    /**
     * The reference instance of <code>jobster.offer_formation</code>
     */
    public static final OfferFormation OFFER_FORMATION = new OfferFormation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OfferFormationRecord> getRecordType() {
        return OfferFormationRecord.class;
    }

    /**
     * The column <code>jobster.offer_formation.id_offer_formation</code>.
     */
    public final TableField<OfferFormationRecord, Integer> ID_OFFER_FORMATION = createField("id_offer_formation", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>jobster.offer_formation.id_offer</code>.
     */
    public final TableField<OfferFormationRecord, Integer> ID_OFFER = createField("id_offer", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>jobster.offer_formation.id_formation</code>.
     */
    public final TableField<OfferFormationRecord, Integer> ID_FORMATION = createField("id_formation", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>jobster.offer_formation</code> table reference
     */
    public OfferFormation() {
        this(DSL.name("offer_formation"), null);
    }

    /**
     * Create an aliased <code>jobster.offer_formation</code> table reference
     */
    public OfferFormation(String alias) {
        this(DSL.name(alias), OFFER_FORMATION);
    }

    /**
     * Create an aliased <code>jobster.offer_formation</code> table reference
     */
    public OfferFormation(Name alias) {
        this(alias, OFFER_FORMATION);
    }

    private OfferFormation(Name alias, Table<OfferFormationRecord> aliased) {
        this(alias, aliased, null);
    }

    private OfferFormation(Name alias, Table<OfferFormationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> OfferFormation(Table<O> child, ForeignKey<O, OfferFormationRecord> key) {
        super(child, key, OFFER_FORMATION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Jobster.JOBSTER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.OFFER_FORMATION_FK_OFFER_FORMATION_FORMATION_IDX, Indexes.OFFER_FORMATION_FK_OFFER_FORMATION_OFFER_IDX, Indexes.OFFER_FORMATION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<OfferFormationRecord, Integer> getIdentity() {
        return Keys.IDENTITY_OFFER_FORMATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OfferFormationRecord> getPrimaryKey() {
        return Keys.KEY_OFFER_FORMATION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OfferFormationRecord>> getKeys() {
        return Arrays.<UniqueKey<OfferFormationRecord>>asList(Keys.KEY_OFFER_FORMATION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<OfferFormationRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<OfferFormationRecord, ?>>asList(Keys.FK_OFFER_FORMATION_OFFER, Keys.FK_OFFER_FORMATION_FORMATION);
    }

    public Offers offers() {
        return new Offers(this, Keys.FK_OFFER_FORMATION_OFFER);
    }

    public Formations formations() {
        return new Formations(this, Keys.FK_OFFER_FORMATION_FORMATION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OfferFormation as(String alias) {
        return new OfferFormation(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OfferFormation as(Name alias) {
        return new OfferFormation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OfferFormation rename(String name) {
        return new OfferFormation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OfferFormation rename(Name name) {
        return new OfferFormation(name, null);
    }
}
