/*
 * This file is generated by jOOQ.
 */
package com.jobster.server.model.tables;


import com.jobster.server.model.Indexes;
import com.jobster.server.model.Jobster;
import com.jobster.server.model.Keys;
import com.jobster.server.model.tables.records.UserFormationRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserFormation extends TableImpl<UserFormationRecord> {

    private static final long serialVersionUID = 164648889;

    /**
     * The reference instance of <code>jobster.user_formation</code>
     */
    public static final UserFormation USER_FORMATION = new UserFormation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserFormationRecord> getRecordType() {
        return UserFormationRecord.class;
    }

    /**
     * The column <code>jobster.user_formation.id_user_formation</code>.
     */
    public final TableField<UserFormationRecord, Integer> ID_USER_FORMATION = createField("id_user_formation", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>jobster.user_formation.id_user</code>.
     */
    public final TableField<UserFormationRecord, Integer> ID_USER = createField("id_user", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>jobster.user_formation.id_formation</code>.
     */
    public final TableField<UserFormationRecord, Integer> ID_FORMATION = createField("id_formation", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>jobster.user_formation</code> table reference
     */
    public UserFormation() {
        this(DSL.name("user_formation"), null);
    }

    /**
     * Create an aliased <code>jobster.user_formation</code> table reference
     */
    public UserFormation(String alias) {
        this(DSL.name(alias), USER_FORMATION);
    }

    /**
     * Create an aliased <code>jobster.user_formation</code> table reference
     */
    public UserFormation(Name alias) {
        this(alias, USER_FORMATION);
    }

    private UserFormation(Name alias, Table<UserFormationRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserFormation(Name alias, Table<UserFormationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> UserFormation(Table<O> child, ForeignKey<O, UserFormationRecord> key) {
        super(child, key, USER_FORMATION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Jobster.JOBSTER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.USER_FORMATION_FK_USER_FORMATION_FORMATION_IDX, Indexes.USER_FORMATION_FK_USER_FORMATION_IDX, Indexes.USER_FORMATION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<UserFormationRecord, Integer> getIdentity() {
        return Keys.IDENTITY_USER_FORMATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserFormationRecord> getPrimaryKey() {
        return Keys.KEY_USER_FORMATION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserFormationRecord>> getKeys() {
        return Arrays.<UniqueKey<UserFormationRecord>>asList(Keys.KEY_USER_FORMATION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<UserFormationRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UserFormationRecord, ?>>asList(Keys.FK_USER_FORMATION_USER, Keys.FK_USER_FORMATION_FORMATION);
    }

    public Users users() {
        return new Users(this, Keys.FK_USER_FORMATION_USER);
    }

    public Formations formations() {
        return new Formations(this, Keys.FK_USER_FORMATION_FORMATION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserFormation as(String alias) {
        return new UserFormation(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserFormation as(Name alias) {
        return new UserFormation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserFormation rename(String name) {
        return new UserFormation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserFormation rename(Name name) {
        return new UserFormation(name, null);
    }
}
