/*
 * This file is generated by jOOQ.
 */
package com.jobster.server.model;


import com.jobster.server.model.tables.Companies;
import com.jobster.server.model.tables.Countries;
import com.jobster.server.model.tables.Education;
import com.jobster.server.model.tables.Formations;
import com.jobster.server.model.tables.Idioms;
import com.jobster.server.model.tables.OfferFormation;
import com.jobster.server.model.tables.Offers;
import com.jobster.server.model.tables.OffersSkills;
import com.jobster.server.model.tables.Referrals;
import com.jobster.server.model.tables.Skills;
import com.jobster.server.model.tables.UserFormation;
import com.jobster.server.model.tables.UserIdiom;
import com.jobster.server.model.tables.Users;
import com.jobster.server.model.tables.UsersSkills;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>jobster</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index COMPANIES_PRIMARY = Indexes0.COMPANIES_PRIMARY;
    public static final Index COMPANIES_WRWEG_IDX = Indexes0.COMPANIES_WRWEG_IDX;
    public static final Index COUNTRIES_PRIMARY = Indexes0.COUNTRIES_PRIMARY;
    public static final Index EDUCATION_FK_USER_ID_IDX = Indexes0.EDUCATION_FK_USER_ID_IDX;
    public static final Index EDUCATION_PRIMARY = Indexes0.EDUCATION_PRIMARY;
    public static final Index FORMATIONS_PRIMARY = Indexes0.FORMATIONS_PRIMARY;
    public static final Index IDIOMS_PRIMARY = Indexes0.IDIOMS_PRIMARY;
    public static final Index OFFERS_FK_OFFER_COMPANY_IDX = Indexes0.OFFERS_FK_OFFER_COMPANY_IDX;
    public static final Index OFFERS_PRIMARY = Indexes0.OFFERS_PRIMARY;
    public static final Index OFFERS_SKILLS_OFFER_SKILLS_OFFER_IDX = Indexes0.OFFERS_SKILLS_OFFER_SKILLS_OFFER_IDX;
    public static final Index OFFERS_SKILLS_OFFER_SKILLS_SKILL_IDX = Indexes0.OFFERS_SKILLS_OFFER_SKILLS_SKILL_IDX;
    public static final Index OFFERS_SKILLS_PRIMARY = Indexes0.OFFERS_SKILLS_PRIMARY;
    public static final Index OFFER_FORMATION_FK_OFFER_FORMATION_FORMATION_IDX = Indexes0.OFFER_FORMATION_FK_OFFER_FORMATION_FORMATION_IDX;
    public static final Index OFFER_FORMATION_FK_OFFER_FORMATION_OFFER_IDX = Indexes0.OFFER_FORMATION_FK_OFFER_FORMATION_OFFER_IDX;
    public static final Index OFFER_FORMATION_PRIMARY = Indexes0.OFFER_FORMATION_PRIMARY;
    public static final Index REFERRALS_CANDIDATO_IDX = Indexes0.REFERRALS_CANDIDATO_IDX;
    public static final Index REFERRALS_FK_OFFER_IDX = Indexes0.REFERRALS_FK_OFFER_IDX;
    public static final Index REFERRALS_JOBSTER_IDX = Indexes0.REFERRALS_JOBSTER_IDX;
    public static final Index REFERRALS_PRIMARY = Indexes0.REFERRALS_PRIMARY;
    public static final Index SKILLS_PRIMARY = Indexes0.SKILLS_PRIMARY;
    public static final Index USERS_PRIMARY = Indexes0.USERS_PRIMARY;
    public static final Index USERS_SKILLS_PRIMARY = Indexes0.USERS_SKILLS_PRIMARY;
    public static final Index USERS_SKILLS_SKILL_USER_IDX = Indexes0.USERS_SKILLS_SKILL_USER_IDX;
    public static final Index USERS_SKILLS_USERS_SKILLS_SKILL_IDX = Indexes0.USERS_SKILLS_USERS_SKILLS_SKILL_IDX;
    public static final Index USER_FORMATION_FK_USER_FORMATION_FORMATION_IDX = Indexes0.USER_FORMATION_FK_USER_FORMATION_FORMATION_IDX;
    public static final Index USER_FORMATION_FK_USER_FORMATION_IDX = Indexes0.USER_FORMATION_FK_USER_FORMATION_IDX;
    public static final Index USER_FORMATION_PRIMARY = Indexes0.USER_FORMATION_PRIMARY;
    public static final Index USER_IDIOM_PRIMARY = Indexes0.USER_IDIOM_PRIMARY;
    public static final Index USER_IDIOM_USER_IDIOM_IDIOM_IDX = Indexes0.USER_IDIOM_USER_IDIOM_IDIOM_IDX;
    public static final Index USER_IDIOM_USUARIO_IDIOMA_IDX = Indexes0.USER_IDIOM_USUARIO_IDIOMA_IDX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index COMPANIES_PRIMARY = Internal.createIndex("PRIMARY", Companies.COMPANIES, new OrderField[] { Companies.COMPANIES.ID_COMPANY }, true);
        public static Index COMPANIES_WRWEG_IDX = Internal.createIndex("wrweg_idx", Companies.COMPANIES, new OrderField[] { Companies.COMPANIES.ID_COUNTRY }, false);
        public static Index COUNTRIES_PRIMARY = Internal.createIndex("PRIMARY", Countries.COUNTRIES, new OrderField[] { Countries.COUNTRIES.ID_COUNTRY }, true);
        public static Index EDUCATION_FK_USER_ID_IDX = Internal.createIndex("FK_user_id_idx", Education.EDUCATION, new OrderField[] { Education.EDUCATION.ID_USER }, false);
        public static Index EDUCATION_PRIMARY = Internal.createIndex("PRIMARY", Education.EDUCATION, new OrderField[] { Education.EDUCATION.ID_EDUCATION }, true);
        public static Index FORMATIONS_PRIMARY = Internal.createIndex("PRIMARY", Formations.FORMATIONS, new OrderField[] { Formations.FORMATIONS.ID_FORMATION }, true);
        public static Index IDIOMS_PRIMARY = Internal.createIndex("PRIMARY", Idioms.IDIOMS, new OrderField[] { Idioms.IDIOMS.ID_IDIOM }, true);
        public static Index OFFERS_FK_OFFER_COMPANY_IDX = Internal.createIndex("FK_OFFER_COMPANY_idx", Offers.OFFERS, new OrderField[] { Offers.OFFERS.ID_COMPANY }, false);
        public static Index OFFERS_PRIMARY = Internal.createIndex("PRIMARY", Offers.OFFERS, new OrderField[] { Offers.OFFERS.ID_OFFER }, true);
        public static Index OFFERS_SKILLS_OFFER_SKILLS_OFFER_IDX = Internal.createIndex("offer_skills_offer_idx", OffersSkills.OFFERS_SKILLS, new OrderField[] { OffersSkills.OFFERS_SKILLS.ID_OFFER }, false);
        public static Index OFFERS_SKILLS_OFFER_SKILLS_SKILL_IDX = Internal.createIndex("offer_skills_skill_idx", OffersSkills.OFFERS_SKILLS, new OrderField[] { OffersSkills.OFFERS_SKILLS.ID_SKILL }, false);
        public static Index OFFERS_SKILLS_PRIMARY = Internal.createIndex("PRIMARY", OffersSkills.OFFERS_SKILLS, new OrderField[] { OffersSkills.OFFERS_SKILLS.ID_OFFER_SKILL }, true);
        public static Index OFFER_FORMATION_FK_OFFER_FORMATION_FORMATION_IDX = Internal.createIndex("FK_OFFER_FORMATION_FORMATION_idx", OfferFormation.OFFER_FORMATION, new OrderField[] { OfferFormation.OFFER_FORMATION.ID_FORMATION }, false);
        public static Index OFFER_FORMATION_FK_OFFER_FORMATION_OFFER_IDX = Internal.createIndex("FK_OFFER_FORMATION_OFFER_idx", OfferFormation.OFFER_FORMATION, new OrderField[] { OfferFormation.OFFER_FORMATION.ID_OFFER }, false);
        public static Index OFFER_FORMATION_PRIMARY = Internal.createIndex("PRIMARY", OfferFormation.OFFER_FORMATION, new OrderField[] { OfferFormation.OFFER_FORMATION.ID_OFFER_FORMATION }, true);
        public static Index REFERRALS_CANDIDATO_IDX = Internal.createIndex("candidato_idx", Referrals.REFERRALS, new OrderField[] { Referrals.REFERRALS.ID_CANDIDATE }, false);
        public static Index REFERRALS_FK_OFFER_IDX = Internal.createIndex("fk_offer_idx", Referrals.REFERRALS, new OrderField[] { Referrals.REFERRALS.ID_OFFER }, false);
        public static Index REFERRALS_JOBSTER_IDX = Internal.createIndex("jobster_idx", Referrals.REFERRALS, new OrderField[] { Referrals.REFERRALS.ID_JOBSTER }, false);
        public static Index REFERRALS_PRIMARY = Internal.createIndex("PRIMARY", Referrals.REFERRALS, new OrderField[] { Referrals.REFERRALS.ID_REFERRAL }, true);
        public static Index SKILLS_PRIMARY = Internal.createIndex("PRIMARY", Skills.SKILLS, new OrderField[] { Skills.SKILLS.ID_SKILL }, true);
        public static Index USERS_PRIMARY = Internal.createIndex("PRIMARY", Users.USERS, new OrderField[] { Users.USERS.ID_USER }, true);
        public static Index USERS_SKILLS_PRIMARY = Internal.createIndex("PRIMARY", UsersSkills.USERS_SKILLS, new OrderField[] { UsersSkills.USERS_SKILLS.ID_USER_SKILL }, true);
        public static Index USERS_SKILLS_SKILL_USER_IDX = Internal.createIndex("skill_user_idx", UsersSkills.USERS_SKILLS, new OrderField[] { UsersSkills.USERS_SKILLS.ID_USER }, false);
        public static Index USERS_SKILLS_USERS_SKILLS_SKILL_IDX = Internal.createIndex("users_skills_skill_idx", UsersSkills.USERS_SKILLS, new OrderField[] { UsersSkills.USERS_SKILLS.ID_SKILL }, false);
        public static Index USER_FORMATION_FK_USER_FORMATION_FORMATION_IDX = Internal.createIndex("FK_USER_FORMATION_FORMATION_idx", UserFormation.USER_FORMATION, new OrderField[] { UserFormation.USER_FORMATION.ID_FORMATION }, false);
        public static Index USER_FORMATION_FK_USER_FORMATION_IDX = Internal.createIndex("FK_USER_FORMATION_idx", UserFormation.USER_FORMATION, new OrderField[] { UserFormation.USER_FORMATION.ID_USER }, false);
        public static Index USER_FORMATION_PRIMARY = Internal.createIndex("PRIMARY", UserFormation.USER_FORMATION, new OrderField[] { UserFormation.USER_FORMATION.ID_USER_FORMATION }, true);
        public static Index USER_IDIOM_PRIMARY = Internal.createIndex("PRIMARY", UserIdiom.USER_IDIOM, new OrderField[] { UserIdiom.USER_IDIOM.ID_USER_IDIOM }, true);
        public static Index USER_IDIOM_USER_IDIOM_IDIOM_IDX = Internal.createIndex("user_idiom_idiom_idx", UserIdiom.USER_IDIOM, new OrderField[] { UserIdiom.USER_IDIOM.ID_IDIOM }, false);
        public static Index USER_IDIOM_USUARIO_IDIOMA_IDX = Internal.createIndex("usuario_idioma_idx", UserIdiom.USER_IDIOM, new OrderField[] { UserIdiom.USER_IDIOM.ID_USER }, false);
    }
}
