/*
 * This file is generated by jOOQ.
 */
package com.jobster.server.model.tables.records;


import com.jobster.server.model.tables.Companies;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompaniesRecord extends UpdatableRecordImpl<CompaniesRecord> implements Record13<Integer, Integer, Integer, String, String, String, String, String, String, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1628105737;

    /**
     * Setter for <code>jobster.companies.id_company</code>.
     */
    public void setIdCompany(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>jobster.companies.id_company</code>.
     */
    public Integer getIdCompany() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jobster.companies.id_country</code>.
     */
    public void setIdCountry(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>jobster.companies.id_country</code>.
     */
    public Integer getIdCountry() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>jobster.companies.cif</code>.
     */
    public void setCif(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>jobster.companies.cif</code>.
     */
    public Integer getCif() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>jobster.companies.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>jobster.companies.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>jobster.companies.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>jobster.companies.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>jobster.companies.path_img</code>.
     */
    public void setPathImg(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>jobster.companies.path_img</code>.
     */
    public String getPathImg() {
        return (String) get(5);
    }

    /**
     * Setter for <code>jobster.companies.website</code>.
     */
    public void setWebsite(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>jobster.companies.website</code>.
     */
    public String getWebsite() {
        return (String) get(6);
    }

    /**
     * Setter for <code>jobster.companies.phone</code>.
     */
    public void setPhone(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>jobster.companies.phone</code>.
     */
    public String getPhone() {
        return (String) get(7);
    }

    /**
     * Setter for <code>jobster.companies.email</code>.
     */
    public void setEmail(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>jobster.companies.email</code>.
     */
    public String getEmail() {
        return (String) get(8);
    }

    /**
     * Setter for <code>jobster.companies.adress</code>.
     */
    public void setAdress(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>jobster.companies.adress</code>.
     */
    public String getAdress() {
        return (String) get(9);
    }

    /**
     * Setter for <code>jobster.companies.city</code>.
     */
    public void setCity(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>jobster.companies.city</code>.
     */
    public String getCity() {
        return (String) get(10);
    }

    /**
     * Setter for <code>jobster.companies.date_created</code>.
     */
    public void setDateCreated(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>jobster.companies.date_created</code>.
     */
    public Timestamp getDateCreated() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>jobster.companies.date_modification</code>.
     */
    public void setDateModification(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>jobster.companies.date_modification</code>.
     */
    public Timestamp getDateModification() {
        return (Timestamp) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Integer, Integer, String, String, String, String, String, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Integer, Integer, String, String, String, String, String, String, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Companies.COMPANIES.ID_COMPANY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Companies.COMPANIES.ID_COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Companies.COMPANIES.CIF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Companies.COMPANIES.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Companies.COMPANIES.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Companies.COMPANIES.PATH_IMG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Companies.COMPANIES.WEBSITE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Companies.COMPANIES.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Companies.COMPANIES.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Companies.COMPANIES.ADRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Companies.COMPANIES.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return Companies.COMPANIES.DATE_CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return Companies.COMPANIES.DATE_MODIFICATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getIdCompany();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getIdCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getCif();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getPathImg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getWebsite();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getAdress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component13() {
        return getDateModification();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdCompany();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCif();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPathImg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getWebsite();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getAdress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getDateModification();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompaniesRecord value1(Integer value) {
        setIdCompany(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompaniesRecord value2(Integer value) {
        setIdCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompaniesRecord value3(Integer value) {
        setCif(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompaniesRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompaniesRecord value5(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompaniesRecord value6(String value) {
        setPathImg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompaniesRecord value7(String value) {
        setWebsite(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompaniesRecord value8(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompaniesRecord value9(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompaniesRecord value10(String value) {
        setAdress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompaniesRecord value11(String value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompaniesRecord value12(Timestamp value) {
        setDateCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompaniesRecord value13(Timestamp value) {
        setDateModification(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompaniesRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, Timestamp value12, Timestamp value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CompaniesRecord
     */
    public CompaniesRecord() {
        super(Companies.COMPANIES);
    }

    /**
     * Create a detached, initialised CompaniesRecord
     */
    public CompaniesRecord(Integer idCompany, Integer idCountry, Integer cif, String name, String description, String pathImg, String website, String phone, String email, String adress, String city, Timestamp dateCreated, Timestamp dateModification) {
        super(Companies.COMPANIES);

        set(0, idCompany);
        set(1, idCountry);
        set(2, cif);
        set(3, name);
        set(4, description);
        set(5, pathImg);
        set(6, website);
        set(7, phone);
        set(8, email);
        set(9, adress);
        set(10, city);
        set(11, dateCreated);
        set(12, dateModification);
    }
}
