/*
 * This file is generated by jOOQ.
 */
package com.jobster.server.model.tables.records;


import com.jobster.server.model.tables.Education;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EducationRecord extends UpdatableRecordImpl<EducationRecord> implements Record9<Integer, Integer, String, Timestamp, Timestamp, String, String, String, Timestamp> {

    private static final long serialVersionUID = 379288048;

    /**
     * Setter for <code>jobster.education.id_education</code>.
     */
    public void setIdEducation(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>jobster.education.id_education</code>.
     */
    public Integer getIdEducation() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jobster.education.id_user</code>.
     */
    public void setIdUser(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>jobster.education.id_user</code>.
     */
    public Integer getIdUser() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>jobster.education.school-name</code>.
     */
    public void setSchoolName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>jobster.education.school-name</code>.
     */
    public String getSchoolName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>jobster.education.start-date</code>.
     */
    public void setStartDate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>jobster.education.start-date</code>.
     */
    public Timestamp getStartDate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>jobster.education.end-date</code>.
     */
    public void setEndDate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>jobster.education.end-date</code>.
     */
    public Timestamp getEndDate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>jobster.education.degreee</code>.
     */
    public void setDegreee(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>jobster.education.degreee</code>.
     */
    public String getDegreee() {
        return (String) get(5);
    }

    /**
     * Setter for <code>jobster.education.activities</code>.
     */
    public void setActivities(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>jobster.education.activities</code>.
     */
    public String getActivities() {
        return (String) get(6);
    }

    /**
     * Setter for <code>jobster.education.notes</code>.
     */
    public void setNotes(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>jobster.education.notes</code>.
     */
    public String getNotes() {
        return (String) get(7);
    }

    /**
     * Setter for <code>jobster.education.date_created</code>.
     */
    public void setDateCreated(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>jobster.education.date_created</code>.
     */
    public Timestamp getDateCreated() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, String, Timestamp, Timestamp, String, String, String, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, String, Timestamp, Timestamp, String, String, String, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Education.EDUCATION.ID_EDUCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Education.EDUCATION.ID_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Education.EDUCATION.SCHOOL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Education.EDUCATION.START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Education.EDUCATION.END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Education.EDUCATION.DEGREEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Education.EDUCATION.ACTIVITIES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Education.EDUCATION.NOTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Education.EDUCATION.DATE_CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getIdEducation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSchoolName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getDegreee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getActivities();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getNotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdEducation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSchoolName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDegreee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getActivities();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getNotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EducationRecord value1(Integer value) {
        setIdEducation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EducationRecord value2(Integer value) {
        setIdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EducationRecord value3(String value) {
        setSchoolName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EducationRecord value4(Timestamp value) {
        setStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EducationRecord value5(Timestamp value) {
        setEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EducationRecord value6(String value) {
        setDegreee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EducationRecord value7(String value) {
        setActivities(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EducationRecord value8(String value) {
        setNotes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EducationRecord value9(Timestamp value) {
        setDateCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EducationRecord values(Integer value1, Integer value2, String value3, Timestamp value4, Timestamp value5, String value6, String value7, String value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EducationRecord
     */
    public EducationRecord() {
        super(Education.EDUCATION);
    }

    /**
     * Create a detached, initialised EducationRecord
     */
    public EducationRecord(Integer idEducation, Integer idUser, String schoolName, Timestamp startDate, Timestamp endDate, String degreee, String activities, String notes, Timestamp dateCreated) {
        super(Education.EDUCATION);

        set(0, idEducation);
        set(1, idUser);
        set(2, schoolName);
        set(3, startDate);
        set(4, endDate);
        set(5, degreee);
        set(6, activities);
        set(7, notes);
        set(8, dateCreated);
    }
}
