/*
 * This file is generated by jOOQ.
 */
package com.jobster.server.model.tables.records;


import com.jobster.server.model.tables.Idioms;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IdiomsRecord extends UpdatableRecordImpl<IdiomsRecord> implements Record4<Integer, String, Integer, Timestamp> {

    private static final long serialVersionUID = -1050774307;

    /**
     * Setter for <code>jobster.idioms.id_idiom</code>.
     */
    public void setIdIdiom(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>jobster.idioms.id_idiom</code>.
     */
    public Integer getIdIdiom() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jobster.idioms.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jobster.idioms.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jobster.idioms.level</code>.
     */
    public void setLevel(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>jobster.idioms.level</code>.
     */
    public Integer getLevel() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>jobster.idioms.date_created</code>.
     */
    public void setDateCreated(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>jobster.idioms.date_created</code>.
     */
    public Timestamp getDateCreated() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Idioms.IDIOMS.ID_IDIOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Idioms.IDIOMS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Idioms.IDIOMS.LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Idioms.IDIOMS.DATE_CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getIdIdiom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdIdiom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IdiomsRecord value1(Integer value) {
        setIdIdiom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IdiomsRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IdiomsRecord value3(Integer value) {
        setLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IdiomsRecord value4(Timestamp value) {
        setDateCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IdiomsRecord values(Integer value1, String value2, Integer value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IdiomsRecord
     */
    public IdiomsRecord() {
        super(Idioms.IDIOMS);
    }

    /**
     * Create a detached, initialised IdiomsRecord
     */
    public IdiomsRecord(Integer idIdiom, String name, Integer level, Timestamp dateCreated) {
        super(Idioms.IDIOMS);

        set(0, idIdiom);
        set(1, name);
        set(2, level);
        set(3, dateCreated);
    }
}
