/*
 * This file is generated by jOOQ.
 */
package com.jobster.server.model.tables.records;


import com.jobster.server.model.tables.UsersSkills;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersSkillsRecord extends UpdatableRecordImpl<UsersSkillsRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 2111161131;

    /**
     * Setter for <code>jobster.users_skills.id_user_skill</code>.
     */
    public void setIdUserSkill(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>jobster.users_skills.id_user_skill</code>.
     */
    public Integer getIdUserSkill() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jobster.users_skills.id_user</code>.
     */
    public void setIdUser(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>jobster.users_skills.id_user</code>.
     */
    public Integer getIdUser() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>jobster.users_skills.id_skill</code>.
     */
    public void setIdSkill(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>jobster.users_skills.id_skill</code>.
     */
    public Integer getIdSkill() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UsersSkills.USERS_SKILLS.ID_USER_SKILL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UsersSkills.USERS_SKILLS.ID_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return UsersSkills.USERS_SKILLS.ID_SKILL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getIdUserSkill();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getIdSkill();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdUserSkill();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getIdSkill();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersSkillsRecord value1(Integer value) {
        setIdUserSkill(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersSkillsRecord value2(Integer value) {
        setIdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersSkillsRecord value3(Integer value) {
        setIdSkill(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersSkillsRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersSkillsRecord
     */
    public UsersSkillsRecord() {
        super(UsersSkills.USERS_SKILLS);
    }

    /**
     * Create a detached, initialised UsersSkillsRecord
     */
    public UsersSkillsRecord(Integer idUserSkill, Integer idUser, Integer idSkill) {
        super(UsersSkills.USERS_SKILLS);

        set(0, idUserSkill);
        set(1, idUser);
        set(2, idSkill);
    }
}
